services:
  - service_name: "FIXME"
    from: "0.0.0.0:8080"
    to: "fixme-service-1:8080"
  - service_name: "TiCCket"
    from: "0.0.0.0:1337"
    to: "ticcket-service-1:1337"
  - service_name: "python-service"
    from: "localhost:3000"
    to: "localhost:8000"